WORDNIK_API_KEY: 948tyh39g8h34p89h4gp398gh0309h039504g498H
WORDNIK_USERNAME: exmapleusername
WORDNIK_PASSWORD: examplepassword

NEWRELIC_LICENSE: a6fg1d5e3b7849c2

ADSENSE_CLIENT: ca-pub-XXXXXXXXXXXXXXXX
ADSENSE_SLOT: "1234567890"
ADS: "true"

development:
  HOST_DOMAIN: homophone-localhost.com
  GOOGLE_ANALYTICS_ACCOUNT: UA-XXXXXXXX-3
  FB_APP_ID: "123451234512345"
  FB_APP_SECRET: abcdefg12345abcdefg12345abcdefg1
  ADS: "false"

staging:
  HOST_DOMAIN: homophone-staging.herokuapp.com
  GOOGLE_ANALYTICS_ACCOUNT: UA-XXXXXXXX-2
  FB_APP_ID: "123451234512345"
  FB_APP_SECRET: abcdefg12345abcdefg12345abcdefg1

production:
  HOST_DOMAIN: www.homophone.com
  GOOGLE_ANALYTICS_ACCOUNT: UA-XXXXXXXX-1
  FB_APP_ID: "123451234512345"
  FB_APP_SECRET: abcdefg12345abcdefg12345abcdefg1
