default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: homophone_development

test:
  <<: *default
  host: localhost
  database: homophone_test
